spring:
  redis:
    host: "localhost"
    port: 63790
postgres:
  driver: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:54320/hse"
  password: "strong password"
  login: "local_app"
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
server:
  port: 8080
logging:
  level:
    org.db.intorduction.cache.simple.demonstration: debug
    root: info